server:
  port: 8763

spring:
  application:
    name: microservice-provider-user
    
eureka:
  client:
    service-url:
      defaultZone: http://peer1:8761/eureka/,http://peer2:8762/eureka/
  instance:
    prefer-ip-address: true