server:
  port: 8764

spring:
  application:
    name: microservice-consumer-movie
    
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    
feign:
  hystrix:
    enabled: true # 该版本的Spring Cloud，Feign默认是不开启Hystrix的。需要设置该属性开启Hystrix