server:
  port: 8764

spring:
  application:
    name: microservice-consumer-movie
    
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    
logging:
  level:
    com.itmuch.cloud.feign.UserFeignClient: DEBUG #将Feign接口的日志级别设置成DEBUG，因为Feign的Logger.Level只对DEBUG做出响应