server:
  port: 8761
  
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defalutZone: http://localhost:8761/eureka/
      
security:
  basic:
    enabled: true   # 开启基于HTTP basic的认证
  user:
    name: admin
    password: admin